version: "2"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/code
        command: [nginx-debug, '-g', 'daemon off;']